### ISSUE TITLE
Attaching an ECS Service to Multiple Target Groups

### ISSUE THREAD

**Issue by denis-singh** [buildkite-plugins/ecs-deploy-buildkite-plugin#100]
Hi,
Does this plugin support attaching a service to multiple target groups?

Thanks

Denis

**Comment by toote** [comment]
Hi @denis-singh, sorry for the delay in getting back to you.

I have reviewed the code and the corresponding AWS APIs and [expected syntax](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/register-multiple-targetgroups.html) and it appears that such scenario is not currently supported.

It may be possible if the service is already created, but that [does not appear to be working at this time either](https://github.com/buildkite-plugins/ecs-deploy-buildkite-plugin/pull/95/#issuecomment-1802700271). We hope that the next major version release with those changes has - hopefully - better compatibility with that scenario as well.

**Comment by toote** [comment]
@denis-singh thanks a lot for your patience! 

While working on support for Fargate and different scenarios (like the one described here) it ended up making a lot more sense to remove the option to create services through the plugin. This way, the amount of TGs/LBs associated with the service would no longer be a concern.

You are more than welcome to test the code of #106 to confirm that it works on your case and let us know if it doesn't so that we can see what we can do about it.
