### ISSUE TITLE
Anyway to just perform update image and not define new definition?

### ISSUE THREAD

**Issue by raymondgao** [buildkite-plugins/ecs-deploy-buildkite-plugin#47]
When I deploy to fargate instance it throws: 

Cannot update a service to add/remove a load balancer. First delete the service and then run again, or rename the service to force a new one to be created. Container config differs | 0s

This is overkill for most folks who just want to  deploy new image. Also why is the json require in buildkite different to the one on AWS? I try to copy task definition JSON as "task-definition" and it complained that format is different.  Do you expect customer we redefine new definition under your format?

**Comment by toote** [comment]
Hi @raymondgao! Since you opened this issue a lot of changes were made to help support fargate so it is possible this is now possible. In addition to that, your idea about having to copy the task definition and getting issues may be addressed when/if the idea mentioned in #43.

If you are still having issues, it would be really interesting to know about them so that we can improve this plugin. If you want to take a stab at adding the functionality that would help you with a PR, even better!
